[package]
name = "pyannote-onnx-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
env_logger = "0.11.8"
hound = "3.5.1"
log = "0.4.27"
ndarray = "0.16.1"
num_cpus = "1.16.0"
ort = { version = "2.0.0-rc.9", features = ["coreml", "tensorrt", "cuda"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false
